# Generated by Django 5.1.6 on 2025-02-17 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('middle_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'Customer',
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Passport_Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizenship', models.CharField(max_length=32)),
                ('birth_date', models.DateField()),
                ('document_ID', models.CharField(max_length=16)),
                ('expire_date', models.DateField()),
                ('birthplace', models.CharField(max_length=32)),
                ('authority', models.CharField(max_length=16)),
                ('issue_date', models.DateField()),
                ('ethnicity', models.CharField(max_length=16)),
                ('personal_number', models.PositiveBigIntegerField()),
                ('customer_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('password_scan', models.ManyToManyField(to='customers.passport_scan')),
            ],
        ),
    ]
