# Generated by Django 5.1.6 on 2025-02-21 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('page_number', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Page Scan',
                'db_table': 'pagescan',
            },
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer_code', models.CharField(max_length=32)),
                ('surname', models.CharField(max_length=32)),
                ('given_name', models.CharField(max_length=16)),
                ('document_number', models.CharField(max_length=9)),
                ('nationality_code', models.CharField(max_length=32)),
                ('birth_date', models.DateField()),
                ('sex', models.CharField(choices=[('m', 'M'), ('f', 'F')], default='M', max_length=1)),
                ('expiry_date', models.DateField()),
                ('optional_data', models.CharField(max_length=14)),
                ('page_scan', models.ManyToManyField(to='customers.pagescan')),
            ],
            options={
                'verbose_name': 'Passport',
                'db_table': 'passport',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.passport')),
            ],
            options={
                'verbose_name': 'Customer',
                'db_table': 'customer',
            },
        ),
    ]
