# Generated by Django 5.1.6 on 2025-02-24 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passport',
            name='optional_data',
        ),
        migrations.AddField(
            model_name='passport',
            name='optional_data_1',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='passport',
            name='optional_data_2',
            field=models.CharField(max_length=14, null=True),
        ),
    ]
