# Generated by Django 5.1.6 on 2025-02-17 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('page_number', models.PositiveIntegerField()),
                ('passport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.passport')),
            ],
            options={
                'verbose_name': 'Page Scan',
            },
        ),
    ]
