# Generated by Django 5.1.6 on 2025-02-25 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_passport_optional_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='given_name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='passport',
            name='issuer_code',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='passport',
            name='nationality_code',
            field=models.CharField(max_length=3),
        ),
    ]
