# Generated by Django 5.1.6 on 2025-02-18 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_pagescan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagescan',
            name='passport',
        ),
        migrations.CreateModel(
            name='PassportScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagescan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.pagescan')),
                ('passport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.passport')),
            ],
        ),
        migrations.AddField(
            model_name='passport',
            name='pagescan',
            field=models.ManyToManyField(through='customers.PassportScan', to='customers.pagescan'),
        ),
    ]
