# Generated by Django 5.1.6 on 2025-02-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_passport_given_name_alter_passport_issuer_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagescan',
            name='page_number',
        ),
        migrations.AddField(
            model_name='pagescan',
            name='mrz_text',
            field=models.CharField(max_length=96, null=True),
        ),
    ]
