# Generated by Django 5.1.6 on 2025-02-18 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_remove_pagescan_passport_passportscan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passport',
            name='password_scan',
        ),
        migrations.AlterModelOptions(
            name='passport',
            options={'verbose_name': 'Passport'},
        ),
        migrations.DeleteModel(
            name='Passport_Scan',
        ),
    ]
