# Generated by Django 5.1.6 on 2025-02-18 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_remove_passport_password_scan_alter_passport_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passport',
            old_name='pagescan',
            new_name='page_scan',
        ),
        migrations.RenameField(
            model_name='passportscan',
            old_name='pagescan',
            new_name='page_scan',
        ),
    ]
