# Generated by Django 5.1.6 on 2025-02-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_remove_pagescan_page_number_pagescan_mrz_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
