# Generated by Django 5.1.6 on 2025-02-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_rename_pagescan_passport_page_scan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passport',
            name='gender',
            field=models.CharField(choices=[('м', 'М'), ('ж', 'Ж')], default='М', max_length=1),
        ),
    ]
