# Generated by Django 5.1.6 on 2025-02-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_alter_customer_address_alter_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='issuer_code',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='passport',
            name='nationality_code',
            field=models.CharField(max_length=3),
        ),
    ]
