# Generated by Django 5.1.6 on 2025-02-27 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_alter_passport_issuer_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 27, 15, 3, 34, 135899)),
        ),
        migrations.AddField(
            model_name='pagescan',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 27, 15, 3, 34, 135899)),
        ),
        migrations.AddField(
            model_name='passport',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 27, 15, 3, 34, 135899)),
        ),
    ]
