# Generated by Django 5.1.6 on 2025-02-19 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_pagescan_owner_passport_owner_passportscan_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagescan',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='passport',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='passportscan',
            name='owner',
        ),
    ]
