# Generated by Django 5.1.6 on 2025-02-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_customer_created_pagescan_created_passport_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='pagescan',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='passport',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
