# Generated by Django 5.1.6 on 2025-02-19 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_remove_pagescan_owner_remove_passport_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='owner',
        ),
    ]
